export default [
    {
      path:"/",
      name:"Layout",
      component:()=>import("../views/LayoutView.vue"),
      redirect:"/index",
      children:[
        {
            path:"/index",
            name:"index",
            component:()=>import("@/views/index/HomeIndex.vue")
        },
        {
          path:"/orders/list",
          name:"order_list",
          component:()=>import("@/views/orders/OrderList.vue"),
          meta:{bread:["订单管理","订单列表"]}
        },
        {
          path:"/waybill/in",
          name:"waybill_register",
          component:()=>import("@/views/wayBill/WayBillRegister"),
          meta:{bread:["运单管理","运单录入"]}
        },
        {
          path:"/waybill/list",
          name:"waybill_list",
          component:()=>import("@/views/wayBill/WayBillList"),
          meta:{bread:["运单管理","运单列表"],keepAlive:true}
        },
        {
          path:"/waybill/detail",
          name:"waybill_detail",
          component:()=>import("@/views/wayBill/WayBillDetail"),
          meta:{bread:["运单管理","运单列表","列表详情"],isFromDetail:false}
        },
        {
          path:"/depart/data",
          name:"depart_data",
          component:()=>import("@/views/depart/DepartData"),
          meta:{bread:["发车管理","发车数据单"]}
        },
        {
          path:"/depart/data/detail",
          name:"depart_data_detail",
          component:()=>import("@/views/depart/DepartDataDetail"),
          meta:{bread:["发车管理","发车数据单","数据单详情"],isFromDetail:false}
        },
        {
          path:"/carrier/list",
          name:"carrier_list",
          component:()=>import("@/views/CommonCarrier/CarrierList"),
          meta:{bread:["承运商管理/承运商列表"]}
        },
        {
          path:"/carrier/trucks",
          name:"carrier_trucks",
          component:()=>import("@/views/CommonCarrier/TrucksList"),
          meta:{bread:["承运商管理/车辆列表"]}
        },
        {
          path:"/carrier/driver",
          name:"carrier_driver",
          component:()=>import("@/views/CommonCarrier/DriverList"),
          meta:{bread:["承运商管理/司机列表"]}
        },
        {
          path:"/customer",
          name:"customer_management",
          component:()=>import("@/views/client/CustomerManagement"),
          meta:{bread:["客户管理"]}
        },
        {
          path:"/customer/detail",
          name:"customer_detail",
          component:()=>import("@/views/client/CustomerDetail"),
          meta:{bread:["客户管理/客户详情"]}
        },
        {
          path:"/customer/info",
          name:"customer_info",
          component:()=>import("@/views/finance/CustomerStatement"),
          meta:{bread:["财务管理/客户对账单"]}
        },
        {
          path:"/record",
          name:"record",
          component:()=>import("@/views/finance/CarriesStatement"),
          meta:{bread:["财务管理/承运商对账单"]}
        },
        {
          path:"/driver",
          name:"driver",
          component:()=>import("@/views/finance/DriverStatement"),
          meta:{bread:["财务管理/司机对账单"]}
        },
        {
          path:"/personal",
          name:"personal",
          component:()=>import("@/views/PersonalCenter/PersonalCenter"),
          meta:{bread:["个人中心"]}
        }
      ]
    },
    {
     path:"/Login",
     name:"Login",
     component:()=>import("../views/LoginView.vue")
    }
   
  ]